### ISSUE TITLE
Crash when debug model JAXBException

### ISSUE THREAD

**Issue by marvinvis** [eclipse/poosl#53]
1. Follow the installation model.
2. debug the producer consumer example 
3. Exception popup dialog showing:
```
An internal error occurred during: "Launching model.poosl".
javax/xml/bind/JAXBException
```
expected is a simuation trace visible.

**Version information:**
Version: 2024-06 (4.32.0)
Build id: 20240606-1231

POOSL IDE	1.0.4.v20230526-1449	org.eclipse.poosl.feature.feature.group	TNO/ESI

Rotalumis	4.3.0.202112210930	nl.tue.rotalumis.sdk.feature.group	TU/e

POOSL Sirius ELK integration	1.0.4.v20230526-1449	org.eclipse.poosl.sirius.elk.feature.feature.group	Obeo

**logging**;
```
!ENTRY org.eclipse.core.jobs 4 2 2024-08-26 16:42:55.063
!MESSAGE An internal error occurred during: "Launching model.poosl".
!STACK 0
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.eclipse.poosl.rotalumisclient.launch.LaunchDelegate.launch(LaunchDelegate.java:217)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:805)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:716)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1054)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1257)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException cannot be found by org.eclipse.poosl.rotalumisclient_1.0.4.v20230526-1449
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:562)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:557)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 6 more
```

Related information: [[How to resolve java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception)](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception)

**Comment by wpiers** [comment]
A fix has been implemented in https://github.com/eclipse/poosl/commit/fb8559e4f0a380b1a20a066cacfd98c012b682b4
